---
title: "Regression Modelling, Algorithmic Trading - 2 Day Prediction"
author: "Patrick de Guzman"
date: "16/08/2020"
output: html_document
---

```{r libraries, message = FALSE, warning = FALSE }
library(data.table)
library(forecast)
library(dplyr)
library(caret)
library(readr)
```

```{r training data, message = FALSE}
df <- list.files(path = 'lm_objects/training/feature_data', full.names = TRUE) %>% 
  lapply(read_csv) %>% 
  bind_rows %>%
  data.frame
df <- df[-c(1)]
head(df)
```

```{r training/test split}
y_col <- c('next_close_2')
remove_y_cols <- c('next_close', 'next_close_3','next_close_5','next_close_10')

set.seed(1111)
train_ind <- createDataPartition(df[,y_col], times = 1, p = 0.85, list = FALSE)
remove_cols <- c('Date', 'sector', 'Ticker', remove_y_cols)

train <- df[train_ind,]
train_y <- train[y_col]; train <- train[setdiff(names(train), remove_cols)]
test <- df[-train_ind,]
test_y <- test[y_col]; test <- test[setdiff(names(test), remove_cols)]
```

```{r preprocessing}
##Remove near zero variance features and only include non-NA variance cols
nearzeros <- nearZeroVar(train)
train <- train[,-nearzeros]
test <- test[,-nearzeros]

vars <- sapply(train, var); var_cols <- names(na.omit(vars))
train <- train[,var_cols]
test <- test[,var_cols]

##PRINCIPAL COMPONENT ANALYSIS
set.seed(1111)
preProc <- preProcess(train, method = "pca", thresh = 0.9)

trainPC <- predict(preProc, train)
testPC <- predict(preProc, test)
```

```{r modelling}
##MODELLING, FEATURE SELECTION
# fit model 
fitall <- lm(next_close_2 ~ ., data = cbind(trainPC, train_y)) 
# extract p-values
pvals <- summary(fitall)$coefficients[,4] 
# extract coefficients 
coefs <- summary(fitall)$coefficients[,1] 

# extract top features, p-val <= 0.05
top <- data.frame(cbind(coefs, pvals)) 
top <- top[order(top[,2], decreasing = FALSE),]
top <- top[top$pvals <= 0.05, ]; top
features <- c(rownames(top)); features <- features[-1] # remove 'intercept', 1st feature

train <- trainPC[features]; test <- testPC[features]
train <- cbind(train, train_y); test <- cbind(test)
train <- train[!is.infinite(rowSums(train)),]

model <- lm(next_close_2 ~ ., data = train)
```

```{r predictions}
# Predictions -------------------------------------------------------------
predictions <- predict(model, newdata = test)
predicted <- cbind(test, test_y, predictions)
write.csv(predicted,'lm_objects/training/training_predictions_2.csv')
```

```{r save}
# save(nearzeros, file = 'lm_objects/excl_nearzerovar_cols.rda')
# save(var_cols, file = 'lm_objects/incl_var_cols.rda')
# save(preProc, file = "lm_objects/pca_preproc.rda")
# save(features, file = "lm_objects/top_features.rda")
# save(model, file = "lm_objects/regression_model.rda")
# write.csv(predicted,'lm_objects/training/training_predictions.csv')
```